# Generated by Django 3.0.6 on 2020-12-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='acknowledgement',
        ),
    ]
