# Generated by Django 3.0.6 on 2020-11-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='pref_dist',
            field=models.CharField(choices=[('ft', 'ft'), ('m', 'm'), ('mi', 'mi'), ('km', 'km')], default='m', max_length=2),
        ),
        migrations.AddField(
            model_name='workout',
            name='pref_weight',
            field=models.CharField(choices=[('lb', 'lb'), ('kg', 'kg')], default='kg', max_length=2),
        ),
    ]
